### ISSUE TITLE
Replication for true benchmark

### ISSUE THREAD

**Issue by saxenarohit** [asappresearch/scale-score#1]
Hi,

Thanks for sharing your work!
I wanted to replicate results on the True Benchmark. Can you please let me know how were the sentence level scores combined to get a single score for the summary. A single inconsistent sentence makes the whole summary inconsistent I guess. Also the thresholds used at the sentence level.

Thanks.

**Comment by blattimer-asapp** [comment]
Hi there! In accordance with the TRUE benchmark, all labels are evaluated at the single example level rather than at the summary level. That being said, if you would like to combine the scores to achieve a summary level score, I would recommend using `scipy.stats.hmean` to weigh single inconsistent sentences more heavily. I can add this option in the next version :). 

In terms of the optimal threshold to use on the sentence level to create a binary label, this can slightly vary from dataset to dataset so ideally you would have a dev set to tune your threshold on. However, in the lack of a dev set, in our paper we showed that the scale score is well calibrated so you can treat it similar to a probability and set the threshold at ~0.5 where >0.5 is factually consistent, and <0.5 is factually inconsistent.
